# fly.toml file generated for coop-manager-web on 2022-12-29T21:12:21-05:00

app          = "coop-manager-web"
kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[build]
  dockerfile = "Dockerfile"

[env]
  NEXT_PUBLIC_GRAPHQL_URL = "https://api.somervillebikekitchen.org/graphql"
  PORT                    = "3000"

[experimental]
  allowed_public_ports = []
  auto_rollback        = true

[[services]]
  http_checks   = []
  internal_port = 3000
  processes     = ["app"]
  protocol      = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type       = "connections"

  [[services.ports]]
    force_https = true
    handlers    = ["http"]
    port        = 80

  [[services.ports]]
    handlers = ["http", "tls"]
    port     = 443

  [[services.tcp_checks]]
    grace_period  = "1s"
    interval      = "15s"
    restart_limit = 0
    timeout       = "2s"
