// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CoopEvents       string
	Members          string
	MembershipTypes  string
	Memberships      string
	Organizations    string
	SchemaMigrations string
	ShiftAssignments string
	ShiftTerms       string
	ShiftTypes       string
	Shifts           string
}{
	CoopEvents:       "coop_events",
	Members:          "members",
	MembershipTypes:  "membership_types",
	Memberships:      "memberships",
	Organizations:    "organizations",
	SchemaMigrations: "schema_migrations",
	ShiftAssignments: "shift_assignments",
	ShiftTerms:       "shift_terms",
	ShiftTypes:       "shift_types",
	Shifts:           "shifts",
}
