app          = "coop-manager-api"
kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "npm run migrate:deploy -- --schema apps/server/prisma/schema.prisma"

[env]
  PORT           = "5020"
  PRIMARY_REGION = "ewr"

[experimental]
  allowed_public_ports = []
  auto_rollback        = true

[[services]]
  http_checks   = []
  internal_port = 5020
  processes     = ["app"]
  protocol      = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type       = "connections"

  [[services.ports]]
    force_https = true
    handlers    = ["http"]
    port        = 80

  [[services.ports]]
    handlers = ["http", "tls"]
    port     = 443

  [[services.tcp_checks]]
    grace_period  = "1s"
    interval      = "15s"
    restart_limit = 0
    timeout       = "2s"
