name: CI

on:
  push:
    branches: ['main', 'fix/**', 'feat/**']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      # - name: Test
      #   run: pnpm test

  tag:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

  push:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push server image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ${context}/apps/server/Dockerfile
          tags: ${{ steps.release.outputs.tag_name }}

      # - name: Build and push frontend image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     file: ${context}/apps/web/Dockerfile
      #     tags: ${{ steps.release.outputs.tag_name }}
      #     labels: user:app/latest
